name: CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master"]

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies    
      run: sudo apt-get update && sudo apt-get install -y build-essential make doxygen valgrind gdb graphviz

    - name: Build Project
      run: make
      
    - name: Build and Run Tests
      run:  make test
      
    - name: Generate Doxygen Docs
      run: make docs
